# Continuous Integration in Backend workflow
name: CI BE Workflow

on:
  # Workflow runs when pull_request to the main branch  
  push:
    branches:
      - main
  
env:
  PYTHON_VERSION: 3.12.1
  IMAGE_REPO_NAME: backend

jobs:
  lint_job:
    name: linting job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pipenv flake8
  
      - name: Install dependencies
        run: |
          pipenv install
  test_job: 
    name: Tests job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      
      - name: Install tests dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest
  
      - name: Install dependencies
        run: |
          pipenv install
  
      - name: Run tests in backend
        run: | 
          pipenv run test
  build:
    name: build job
    needs: [lint_job, test_job]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Build Docker container image
        run: |
          docker build -t ${{env.IMAGE_REPO_NAME}}:latest .