name: CI Backend 

on:
  pull_request:
    branches: 
      - main

# Define Environment 
env:
  PY_VERSION: 3.12.1
  IMAGE_NAME: backend
jobs:
  linting_job:
    name: linting job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PY_VERSION}}
      
      - name: Install Linting Tools and Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv flake8
  
      - name: Install dependencies
        run: |
          pipenv install
  testing_job: 
    name: testing job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PY_VERSION}}
      
      - name: Install Dependencies in Testing
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest
  
      - name: Install Dependencies
        run: |
          pipenv install
  
      - name: Run Tests in Backend
        run: | 
          pipenv run test
  build:
    name: building job
    needs: [linting_job, testing_job]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: |
          docker build -t ${{env.IMAGE_NAME}}:latest .